apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: mlops-pool
  namespace: metallb-system
spec:
  addresses:
    - __METALLB_POOL_START__-__METALLB_POOL_END__
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: mlops-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - mlops-pool

