apiVersion: v1
kind: Service
metadata:
  name: house-prices-service
  namespace: mlops-apps
spec:
  selector:
    app: house-prices-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
