apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: iris-random-search-01-baseline
  namespace: katib-experiments
spec:
  objective:
    type: maximize
    objectiveMetricName: accuracy
    goal: 0.99
  algorithm:
    algorithmName: random
  parallelTrialCount: 1
  maxTrialCount: 4
  maxFailedTrialCount: 3
  metricsCollectorSpec:
    collector:
      kind: StdOut
  parameters:
    - name: n_estimators
      parameterType: int
      feasibleSpace:
        min: "20"
        max: "120"
    - name: max_depth
      parameterType: int
      feasibleSpace:
        min: "2"
        max: "8"
    - name: min_samples_split
      parameterType: int
      feasibleSpace:
        min: "2"
        max: "10"
  trialTemplate:
    primaryContainerName: trainer
    trialParameters:
      - name: nEstimators
        description: Number of trees
        reference: n_estimators
      - name: maxDepth
        description: Max tree depth
        reference: max_depth
      - name: minSamplesSplit
        description: Minimum samples split
        reference: min_samples_split
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        backoffLimit: 0
        template:
          spec:
            restartPolicy: Never
            containers:
              - name: trainer
                image: mlops-demo:0.2.0
                imagePullPolicy: IfNotPresent
                command:
                  - python
                  - -m
                  - mlops_iris.katib_objective
                  - --n-estimators=${trialParameters.nEstimators}
                  - --max-depth=${trialParameters.maxDepth}
                  - --min-samples-split=${trialParameters.minSamplesSplit}
