apiVersion: v1
kind: Namespace
metadata:
  name: dev-workspace
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops-apps
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: katib-experiments
  labels:
    katib.kubeflow.org/metrics-collector-injection: enabled

