kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: __CLUSTER_NAME__
nodes:
  - role: control-plane
    image: __KIND_NODE_IMAGE__
    extraPortMappings:
      - containerPort: __ISTIO_HTTP_NODEPORT__
        hostPort: 80
        listenAddress: "__INGRESS_EXTERNAL_IP__"
        protocol: TCP
      - containerPort: __ISTIO_HTTPS_NODEPORT__
        hostPort: 443
        listenAddress: "__INGRESS_EXTERNAL_IP__"
        protocol: TCP
      - containerPort: __ISTIO_STATUS_NODEPORT__
        hostPort: 15021
        listenAddress: "127.0.0.1"
        protocol: TCP
    extraMounts:
      - hostPath: __HOST_WORKSPACE_PATH__
        containerPath: __WORKSPACE_NODE_PATH__
  - role: worker
    image: __KIND_NODE_IMAGE__
    extraMounts:
      - hostPath: __HOST_WORKSPACE_PATH__
        containerPath: __WORKSPACE_NODE_PATH__
