kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: __CLUSTER_NAME__
nodes:
  - role: control-plane
    image: __KIND_NODE_IMAGE__
    extraPortMappings:
      - containerPort: __VSCODE_NODEPORT__
        hostPort: 80
        listenAddress: "__VSCODE_EXTERNAL_IP__"
        protocol: TCP
      - containerPort: __KATIB_NODEPORT__
        hostPort: 80
        listenAddress: "__KATIB_EXTERNAL_IP__"
        protocol: TCP
      - containerPort: __IRIS_NODEPORT__
        hostPort: 80
        listenAddress: "__IRIS_EXTERNAL_IP__"
        protocol: TCP
    extraMounts:
      - hostPath: __HOST_WORKSPACE_PATH__
        containerPath: __WORKSPACE_NODE_PATH__
  - role: worker
    image: __KIND_NODE_IMAGE__
    extraMounts:
      - hostPath: __HOST_WORKSPACE_PATH__
        containerPath: __WORKSPACE_NODE_PATH__
