apiVersion: v1
kind: Service
metadata:
  name: katib-public
  namespace: kubeflow
spec:
  type: LoadBalancer
  loadBalancerIP: __KATIB_LOADBALANCER_IP__
  selector:
    app: katib-public-proxy
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: __KATIB_NODEPORT__
