apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode-home
  namespace: dev-workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

